### PR TITLE
Improve Haddock of top level module

### PR DESCRIPTION
**Pull request by tomjaguarpaw**
[It was brought to my attention](https://www.reddit.com/r/haskell/comments/55bvt4/typesafe_printf_with_typeintype/d89e96f) that this wonderful library is hard to understand.

I added some more in-depth and clearer explanations.  Hope that helps!

### CODE REVIEW

**Comment by chrisdone** [comment]
Lovely. I'll merge when I'm back at a computer later today!

**Comment by tomjaguarpaw** [comment]
Did you manage to find a computer? ;-)

**Comment by chrisdone** [comment]
I did, thanks!

**Comment by tomjaguarpaw** [comment]
Any chance of getting a release of this version to Hackage?

**Comment by chrisdone** [comment]
Bumped!

**Comment by tomjaguarpaw** [comment]
Thanks!

**Pull request merged**
